# Generated by Django 3.1.1 on 2021-03-26 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField()),
                ('ethnicity', models.CharField(choices=[('HI', 'Hispanic or Latino'), ('NH', 'Not Hispanic or Latino'), ('OT', 'Other')], default='OT', max_length=2)),
                ('race', models.CharField(choices=[('AI', 'American Indian or Alaska Native'), ('AS', 'Asian'), ('BL', 'Black or African American'), ('NH', 'Native Hawaiian or Other Pacific Islander'), ('WH', 'White'), ('OT', 'Other')], default='OT', max_length=2)),
                ('education', models.CharField(choices=[('NH', 'No High School'), ('HS', 'High School Diploma or GED'), ('AS', 'Assocaite Degree'), ('BS', "Bachelor's Degree"), ('MS', "Master's Degree"), ('DC', 'Doctorate Degree'), ('PD', 'Professional Degree'), ('OT', 'Other')], default='OT', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
