# Generated by Django 3.1.1 on 2021-04-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0003_profile_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.CharField(max_length=1)),
                ('updated', models.DateField(auto_now=True)),
                ('aud', models.DecimalField(decimal_places=2, max_digits=200)),
                ('bgn', models.DecimalField(decimal_places=2, max_digits=200)),
                ('brl', models.DecimalField(decimal_places=2, max_digits=200)),
                ('cad', models.DecimalField(decimal_places=2, max_digits=200)),
                ('chf', models.DecimalField(decimal_places=2, max_digits=200)),
                ('cny', models.DecimalField(decimal_places=2, max_digits=200)),
                ('czk', models.DecimalField(decimal_places=2, max_digits=200)),
                ('dkk', models.DecimalField(decimal_places=2, max_digits=200)),
                ('gbp', models.DecimalField(decimal_places=2, max_digits=200)),
                ('hkd', models.DecimalField(decimal_places=2, max_digits=200)),
                ('hrk', models.DecimalField(decimal_places=2, max_digits=200)),
                ('huf', models.DecimalField(decimal_places=2, max_digits=200)),
                ('idr', models.DecimalField(decimal_places=2, max_digits=200)),
                ('ils', models.DecimalField(decimal_places=2, max_digits=200)),
                ('inr', models.DecimalField(decimal_places=2, max_digits=200)),
                ('isk', models.DecimalField(decimal_places=2, max_digits=200)),
                ('jpy', models.DecimalField(decimal_places=2, max_digits=200)),
                ('krw', models.DecimalField(decimal_places=2, max_digits=200)),
                ('mxn', models.DecimalField(decimal_places=2, max_digits=200)),
                ('myr', models.DecimalField(decimal_places=2, max_digits=200)),
                ('nok', models.DecimalField(decimal_places=2, max_digits=200)),
                ('nzd', models.DecimalField(decimal_places=2, max_digits=200)),
                ('php', models.DecimalField(decimal_places=2, max_digits=200)),
                ('pln', models.DecimalField(decimal_places=2, max_digits=200)),
                ('ron', models.DecimalField(decimal_places=2, max_digits=200)),
                ('rub', models.DecimalField(decimal_places=2, max_digits=200)),
                ('sek', models.DecimalField(decimal_places=2, max_digits=200)),
                ('sgd', models.DecimalField(decimal_places=2, max_digits=200)),
                ('thb', models.DecimalField(decimal_places=2, max_digits=200)),
                ('tury', models.DecimalField(decimal_places=2, max_digits=200)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=200)),
                ('zar', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
    ]
