# Generated by Django 3.1.1 on 2021-04-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0015_auto_20210413_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assets_euro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='income_euro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='liabilties_euro',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
