# Generated by Django 3.1.1 on 2021-04-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0016_auto_20210413_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assets_euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income_euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liabilties_euro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
