# Generated by Django 3.1.1 on 2021-04-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0017_auto_20210413_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='liabilties_euro',
            new_name='liabilities_euro',
        ),
    ]
