# Generated by Django 3.1.1 on 2021-04-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0018_auto_20210413_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='liabilities_euro',
            new_name='debts_euro',
        ),
    ]
