# Generated by Django 3.1.1 on 2021-04-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0019_auto_20210413_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='assets_euro',
            new_name='assets',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='debts_euro',
            new_name='debts',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='income_euro',
            new_name='income',
        ),
    ]
