# Generated by Django 3.1.1 on 2021-10-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0020_auto_20210418_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_year',
            field=models.IntegerField(default=0),
        ),
    ]
