# Generated by Django 3.1.1 on 2021-10-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0022_auto_20211019_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_groun',
            field=models.IntegerField(blank=True, choices=[(10, '0 - 9'), (20, '10 - 19'), (30, '20 - 29'), (40, '30 - 39'), (50, '40 - 49'), (60, '50 - 59'), (70, '60 And Over')], default=10),
        ),
    ]
