# Generated by Django 3.1.1 on 2021-10-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0023_profile_age_groun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age_groun',
            new_name='age_group',
        ),
    ]
