# Generated by Django 3.1.1 on 2021-10-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0024_auto_20211027_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_year',
        ),
    ]
