# Generated by Django 3.1.1 on 2021-10-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0025_remove_profile_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assets',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='debts',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=200),
        ),
    ]
